spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/where_place
    username: root
    password: swacademytest
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        query.in_clause_parameter_padding: true
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8080
